language: objective-c
before_install:
- node --version
- npm --version
- brew update
- brew install casperjs --devel
- npm install -g bower
before_script:
- npm install
- bower install
script:
- npm test
